[package]
name = "komgraf"
version = "0.1.0"
edition = "2021"
author = "TimKahyo"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.0"
env_logger = "0.10"
log = "0.4"
wgpu = "0.18"